### PR TITLE
Excise all trace of folsom/parse_trans

### PR DESCRIPTION
**Pull request by ghost**
@kzemek - I made this to spark off discussion - I want exometer working with modern Erlang (20/21) and Elxir 1.7. To that end I've stripped out folsom, and parse_trans. I still get lots of deprecation warnings but they can be ignored for the time being. We should have a chat about this. B

### CODE REVIEW

**Comment by ghost** [comment]
Uh when I say remove all trace, I mean from the source code, there's still plenty of references in the docs.

**Comment by ghost** [comment]
Just running a build on the master of this project - not my fork - vm custom compiled - without hipe (amongst other things) - got this error : 

```
=INFO REPORT==== 15-Aug-2018::15:43:54 ===
Protocol 'inet_tcp': register/listen error: econnrefused
Attempting to start epmd...
===> Compiling meck
===> Compiling bear
===> Compiling _build/default/lib/bear/src/bear.erl failed
_build/default/lib/bear/src/bear.erl:none: internal error in native_compile;
crash reason: undef

  in function  hipe:compile/4
     called as hipe:compile(bear,[],
 <<70,79,82,49,0,0,83,160,66,69,65,77,65,116,85,56,0,0,5,122,0,0,0,116,4,98,
   101,97,114,14,103,101,116,95,115,116,97,116,105,115,116,105,99,115,5,108,
```

Recompiling my erlangs - this time with hipe support - just mentioning this as another benefit of excising the folsom dep.

**Comment by ghost** [comment]
https://github.com/boundary/bear/blob/0717c73bdedd27055211f9234a6efc5588a1299c/src/bear.erl#L42

**Comment by kzemek** [comment]
LGTM

**Comment by ghost** [comment]
Don't merge. I want to get rid of "hut" as well, like I *really* want to get rid of it.

**Review by fen-pl — APPROVED** [review]

**Comment by fen-pl** [comment]
@bryanhuntesl Please remove hut in separate PR. Let's do it in smaller steps - easier to track and review. :)

**Pull request merged**
